//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPUSER
    {
        public APPUSER()
        {
            this.APPUSERORGANIZATIONs = new HashSet<APPUSERORGANIZATION>();
            this.TEAMEVENTPLAYERROSTERs = new HashSet<TEAMEVENTPLAYERROSTER>();
            this.SHAREKEYs = new HashSet<SHAREKEY>();
            this.APPUSERORGANIZATIONs1 = new HashSet<APPUSERORGANIZATION>();
            this.PAYMENTHISTORies = new HashSet<PAYMENTHISTORY>();
            this.FILECABINETDOCUMENTs = new HashSet<FILECABINETDOCUMENT>();
            this.SHAREDOCUMENTs = new HashSet<SHAREDOCUMENT>();
            this.SHAREDOCUMENTs1 = new HashSet<SHAREDOCUMENT>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> PRIMARYAPPUSERID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATECODE { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILEPHONENUMBER { get; set; }
        public string EMAILADDRESS { get; set; }
        public string EMAILADDRESS2 { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> RELATIONSHIPTYPEID { get; set; }
        public Nullable<int> APPUSERTYPEID { get; set; }
        public Nullable<int> SHAREKEYID { get; set; }
        public Nullable<System.DateTime> SHAREKEYEXPIREDATE { get; set; }
        public Nullable<int> APPUSERSTATUSID { get; set; }
        public string CABINETID { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
    
        public virtual RELATIONSHIPTYPE RELATIONSHIPTYPE { get; set; }
        public virtual APPUSERSTATU APPUSERSTATU { get; set; }
        public virtual ICollection<APPUSERORGANIZATION> APPUSERORGANIZATIONs { get; set; }
        public virtual ICollection<TEAMEVENTPLAYERROSTER> TEAMEVENTPLAYERROSTERs { get; set; }
        public virtual ICollection<SHAREKEY> SHAREKEYs { get; set; }
        public virtual ICollection<APPUSERORGANIZATION> APPUSERORGANIZATIONs1 { get; set; }
        public virtual ICollection<PAYMENTHISTORY> PAYMENTHISTORies { get; set; }
        public virtual ICollection<FILECABINETDOCUMENT> FILECABINETDOCUMENTs { get; set; }
        public virtual ICollection<SHAREDOCUMENT> SHAREDOCUMENTs { get; set; }
        public virtual ICollection<SHAREDOCUMENT> SHAREDOCUMENTs1 { get; set; }
        public virtual APPUSERTYPE APPUSERTYPE { get; set; }
    }
}
