//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COACHSTATU
    {
        public COACHSTATU()
        {
            this.COACHes = new HashSet<COACH>();
            this.COACHes1 = new HashSet<COACH>();
            this.COACHes2 = new HashSet<COACH>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ALLOWADDEVENT { get; set; }
    
        public virtual ICollection<COACH> COACHes { get; set; }
        public virtual ICollection<COACH> COACHes1 { get; set; }
        public virtual ICollection<COACH> COACHes2 { get; set; }
    }
}
