//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTSTATU
    {
        public DOCUMENTSTATU()
        {
            this.FILECABINETDOCUMENTs = new HashSet<FILECABINETDOCUMENT>();
            this.SHAREDOCUMENTs = new HashSet<SHAREDOCUMENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<FILECABINETDOCUMENT> FILECABINETDOCUMENTs { get; set; }
        public virtual ICollection<SHAREDOCUMENT> SHAREDOCUMENTs { get; set; }
    }
}
