//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILLOG
    {
        public int ID { get; set; }
        public string TOEMAILADDRESS { get; set; }
        public string SUBJECTLINE { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
    }
}
