//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyFileItEntities : DbContext
    {
        public MyFileItEntities()
            : base("name=MyFileItEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPUSERSTATU> APPUSERSTATUS { get; set; }
        public virtual DbSet<DOCUMENTSTATU> DOCUMENTSTATUS { get; set; }
        public virtual DbSet<DOCUMENTTYPE> DOCUMENTTYPEs { get; set; }
        public virtual DbSet<ORGANIZATIONSTATU> ORGANIZATIONSTATUS { get; set; }
        public virtual DbSet<ORGANIZATIONTYPE> ORGANIZATIONTYPEs { get; set; }
        public virtual DbSet<RELATIONSHIPTYPE> RELATIONSHIPTYPEs { get; set; }
        public virtual DbSet<SALESREPSTATU> SALESREPSTATUS { get; set; }
        public virtual DbSet<SPORTTYPE> SPORTTYPEs { get; set; }
        public virtual DbSet<TEAMEVENTDOCUMENTSTATU> TEAMEVENTDOCUMENTSTATUS { get; set; }
        public virtual DbSet<PAYMENTTYPE> PAYMENTTYPEs { get; set; }
        public virtual DbSet<SALESREPLEADAREA> SALESREPLEADAREAs { get; set; }
        public virtual DbSet<SHAREKEY> SHAREKEYs { get; set; }
        public virtual DbSet<TEAMEVENTPLAYERROSTER> TEAMEVENTPLAYERROSTERs { get; set; }
        public virtual DbSet<USERSTAGETYPE> USERSTAGETYPEs { get; set; }
        public virtual DbSet<APPUSERORGANIZATION> APPUSERORGANIZATIONs { get; set; }
        public virtual DbSet<PAYMENTHISTORY> PAYMENTHISTORies { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATIONs { get; set; }
        public virtual DbSet<APPUSER> APPUSERs { get; set; }
        public virtual DbSet<COACH> COACHes { get; set; }
        public virtual DbSet<COACHSTATU> COACHSTATUS { get; set; }
        public virtual DbSet<FILECABINETDOCUMENT> FILECABINETDOCUMENTs { get; set; }
        public virtual DbSet<SHAREDOCUMENT> SHAREDOCUMENTs { get; set; }
        public virtual DbSet<EMAILLOG> EMAILLOGs { get; set; }
        public virtual DbSet<APPUSERTYPE> APPUSERTYPEs { get; set; }
        public virtual DbSet<TEAMEVENTDOCUMENT> TEAMEVENTDOCUMENTs { get; set; }
        public virtual DbSet<SALESREP> SALESREPs { get; set; }
        public virtual DbSet<TEAMEVENT> TEAMEVENTs { get; set; }
    }
}
