//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public ORGANIZATION()
        {
            this.APPUSERORGANIZATIONs = new HashSet<APPUSERORGANIZATION>();
            this.COACHes = new HashSet<COACH>();
            this.TEAMEVENTs = new HashSet<TEAMEVENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATECODE { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string CONTACTPERSON { get; set; }
        public string EMAILADDRESS { get; set; }
        public string LOGOIMAGE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> ORGANIZATIONTYPEID { get; set; }
        public Nullable<int> ORGANIZATIONSTATUSID { get; set; }
        public Nullable<int> SALESREPID { get; set; }
        public string DIRECTORNAME { get; set; }
        public string DIRECTOREMAIL { get; set; }
        public string DIRECTORPHONE { get; set; }
        public string ALLOWCOACHTOCREATEEVENTS { get; set; }
        public string CCALLEMAILTODIRECTOR { get; set; }
        public string WHOSPAYING { get; set; }
        public string CABINETID { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public string PROMOCODE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<APPUSERORGANIZATION> APPUSERORGANIZATIONs { get; set; }
        public virtual ORGANIZATIONTYPE ORGANIZATIONTYPE { get; set; }
        public virtual ORGANIZATIONSTATU ORGANIZATIONSTATU { get; set; }
        public virtual ICollection<COACH> COACHes { get; set; }
        public virtual ICollection<TEAMEVENT> TEAMEVENTs { get; set; }
    }
}
