//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATIONSHIPTYPE
    {
        public RELATIONSHIPTYPE()
        {
            this.APPUSERs = new HashSet<APPUSER>();
            this.COACHes = new HashSet<COACH>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<APPUSER> APPUSERs { get; set; }
        public virtual ICollection<COACH> COACHes { get; set; }
    }
}
