//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESREP
    {
        public SALESREP()
        {
            this.SHAREKEYs = new HashSet<SHAREKEY>();
            this.SALESREPLEADAREAs = new HashSet<SALESREPLEADAREA>();
        }
    
        public int ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATECODE { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string CONTACTPERSON { get; set; }
        public string EMAILADDRESS { get; set; }
        public Nullable<int> SALESREPSTATUSID { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<System.DateTime> DEACTIVATEDATE { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual SALESREPSTATU SALESREPSTATU { get; set; }
        public virtual ICollection<SHAREKEY> SHAREKEYs { get; set; }
        public virtual ICollection<SALESREPLEADAREA> SALESREPLEADAREAs { get; set; }
    }
}
