//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESREPLEADAREA
    {
        public int ID { get; set; }
        public int SALESREPID { get; set; }
        public string CITY { get; set; }
        public string STATECODE { get; set; }
        public string ZIPCODE { get; set; }
    
        public virtual SALESREP SALESREP { get; set; }
    }
}
