//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHAREDOCUMENT
    {
        public int ID { get; set; }
        public string DOCUMENTID { get; set; }
        public Nullable<int> TEAMEVENTDOCUMENTID { get; set; }
        public Nullable<int> APPUSERID { get; set; }
        public Nullable<System.DateTime> SCANDATE { get; set; }
        public string COMMENT { get; set; }
        public string LOCATION { get; set; }
        public int DOCUMENTTYPEID { get; set; }
        public int DOCUMENTSTATUSID { get; set; }
        public string EMERGENCY { get; set; }
        public string CABINETID { get; set; }
        public Nullable<System.DateTime> DOCUMENTDATE { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> FILECABINETDOCUMENTID { get; set; }
        public Nullable<System.DateTime> VERIFIEDDATE { get; set; }
        public Nullable<int> VERIFIEDAPPUSERID { get; set; }
        public string EMERGENCYEMAILADDRESS { get; set; }
        public string VIEWDOCUMENTKEY { get; set; }
        public string VIEWED { get; set; }
        public Nullable<System.DateTime> VIEWDATE { get; set; }
        public string ISACTIVE { get; set; }
    
        public virtual APPUSER APPUSER { get; set; }
        public virtual APPUSER APPUSER1 { get; set; }
        public virtual DOCUMENTSTATU DOCUMENTSTATU { get; set; }
        public virtual DOCUMENTTYPE DOCUMENTTYPE { get; set; }
        public virtual FILECABINETDOCUMENT FILECABINETDOCUMENT { get; set; }
        public virtual TEAMEVENTDOCUMENT TEAMEVENTDOCUMENT { get; set; }
    }
}
