//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHAREKEY
    {
        public int ID { get; set; }
        public Nullable<int> APPUSERID { get; set; }
        public Nullable<System.DateTime> PURCHASEDATE { get; set; }
        public string PROMOCODE { get; set; }
        public string LAST4CC { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> SALESREPID { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> PAYMENTTYPEID { get; set; }
        public Nullable<int> PRIMARYAPPUSERID { get; set; }
        public string SHAREKEYCODE { get; set; }
    
        public virtual PAYMENTTYPE PAYMENTTYPE { get; set; }
        public virtual APPUSER APPUSER { get; set; }
        public virtual SALESREP SALESREP { get; set; }
    }
}
