//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMEVENTPLAYERROSTER
    {
        public int ID { get; set; }
        public int TEAMEVENTID { get; set; }
        public Nullable<int> APPUSERID { get; set; }
        public string PLAYERPOSITION { get; set; }
        public Nullable<int> JERSEYNUMBER { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<int> USERSTAGETYPEID { get; set; }
    
        public virtual USERSTAGETYPE USERSTAGETYPE { get; set; }
        public virtual APPUSER APPUSER { get; set; }
        public virtual TEAMEVENT TEAMEVENT { get; set; }
    }
}
