//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMEVENTDOCUMENT
    {
        public TEAMEVENTDOCUMENT()
        {
            this.SHAREDOCUMENTs = new HashSet<SHAREDOCUMENT>();
        }
    
        public int ID { get; set; }
        public int TEAMEVENTID { get; set; }
        public string DOCUMENTNAME { get; set; }
        public string ENTERWHOSCANNED { get; set; }
        public string SCANNAME { get; set; }
        public string MUSTBEVERIFIED { get; set; }
        public Nullable<int> TEAMEVENTDOCUMENTSTATUSID { get; set; }
        public string VERIFIERNAME { get; set; }
        public Nullable<System.DateTime> PLAYERENTEREXPIRATION { get; set; }
        public Nullable<System.DateTime> PLAYERENTERDOCUMENTDATE { get; set; }
        public string ISCOACHDOCUMENT { get; set; }
        public Nullable<System.DateTime> ROSTERCLOSEDATE { get; set; }
    
        public virtual ICollection<SHAREDOCUMENT> SHAREDOCUMENTs { get; set; }
        public virtual TEAMEVENTDOCUMENTSTATU TEAMEVENTDOCUMENTSTATU { get; set; }
        public virtual TEAMEVENT TEAMEVENT { get; set; }
    }
}
