//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMEVENT
    {
        public TEAMEVENT()
        {
            this.COACHes = new HashSet<COACH>();
            this.TEAMEVENTPLAYERROSTERs = new HashSet<TEAMEVENTPLAYERROSTER>();
            this.TEAMEVENTDOCUMENTs = new HashSet<TEAMEVENTDOCUMENT>();
        }
    
        public int ID { get; set; }
        public int ORGANIZATIONID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> YEARCODE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> EXPIRESDATE { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public string ISDELETED { get; set; }
    
        public virtual ICollection<COACH> COACHes { get; set; }
        public virtual ORGANIZATION ORGANIZATION { get; set; }
        public virtual ICollection<TEAMEVENTPLAYERROSTER> TEAMEVENTPLAYERROSTERs { get; set; }
        public virtual ICollection<TEAMEVENTDOCUMENT> TEAMEVENTDOCUMENTs { get; set; }
    }
}
