//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABINETS_ACCESS
    {
        public string CABINETNAME { get; set; }
        public string ACCESSNAME { get; set; }
        public string ACCESSTYPE { get; set; }
        public string FILTERINDEX { get; set; }
        public string FILTERVALUE { get; set; }
        public string UPDATEINDEX { get; set; }
    }
}
