//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABINET
    {
        public string CABINETNAME { get; set; }
        public string CABINETID { get; set; }
        public string CABINETFULLPATH { get; set; }
        public string ACCOUNT { get; set; }
        public string ROOTPATH { get; set; }
        public string OSTOREPATH { get; set; }
        public string WSTOREPATH { get; set; }
        public string TSTOREPATH { get; set; }
        public string ADMINISTRATOR { get; set; }
        public string DESCRIPTION { get; set; }
        public string TEMPLATENAME { get; set; }
        public Nullable<int> SORTORDER { get; set; }
        public string LOOKUPFILEPATH { get; set; }
    }
}
