//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABINETS_LOOKUPFILE
    {
        public string CABINETID { get; set; }
        public string COLUMNNAME { get; set; }
        public int INDEXNO { get; set; }
        public string INDEXNAME { get; set; }
        public string SEARCHCOLUMN { get; set; }
        public string VALIDATECOLUMN { get; set; }
    }
}
