//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERRATE
    {
        public int ID { get; set; }
        public Nullable<int> BREAK { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
    }
}
