//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int CUSTID { get; set; }
        public string USERNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string CC_NAME { get; set; }
        public string CC_ADDRESS1 { get; set; }
        public string CC_ADDRESS2 { get; set; }
        public string CC_CITY { get; set; }
        public string CC_STATE { get; set; }
        public string CC_ZIP { get; set; }
        public string CC_COUNTRY { get; set; }
        public string CC_TYPE { get; set; }
        public string CC_NUM { get; set; }
        public Nullable<int> CC_MONTH { get; set; }
        public Nullable<int> CC_YEAR { get; set; }
        public string CC_CVN { get; set; }
        public string PAYMENTTYPE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> MONTHLYRATE { get; set; }
        public Nullable<decimal> PERIMAGERATE { get; set; }
        public string BILLINGTYPE { get; set; }
        public Nullable<int> MONTHLYSCANCAP { get; set; }
        public Nullable<decimal> DISCOUNTRATE { get; set; }
        public Nullable<decimal> OVERAGERATE { get; set; }
        public string USE_RATES { get; set; }
        public Nullable<decimal> OPEN_BALANCE { get; set; }
        public Nullable<decimal> PREPAID_AMOUNT { get; set; }
        public Nullable<System.DateTime> LASTBILLDATE { get; set; }
        public string COMPANY { get; set; }
        public string PHONE { get; set; }
        public string CONTACTBY { get; set; }
        public Nullable<int> YEARLYBILLEDIMAGES { get; set; }
    }
}
