//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_OUT
    {
        public string EMAIL_ADDRESS { get; set; }
        public string EMAIL_FROM { get; set; }
        public string EMAIL_HOST { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string IS_ACTIVE { get; set; }
        public string IS_ADMIN { get; set; }
        public string FAILURE_MAILBOX { get; set; }
        public string ARCHIVE_MAILBOX { get; set; }
    }
}
