//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public GROUP()
        {
            this.GROUPS_USERS = new HashSet<GROUPS_USERS>();
        }
    
        public string GROUPNAME { get; set; }
        public string ADMINISTRATOR { get; set; }
        public string ACCOUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOGO { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<GROUPS_USERS> GROUPS_USERS { get; set; }
    }
}
