//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS_USERS
    {
        public string GROUPNAME { get; set; }
        public string USERNAME { get; set; }
        public string ACCOUNT { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual USER USER { get; set; }
    }
}
