//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ARCS
    {
        public System.DateTime LOGDATE { get; set; }
        public string CABINETID { get; set; }
        public string SCANNERID { get; set; }
        public string MSG { get; set; }
    }
}
