//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ORDERNO { get; set; }
        public int CUSTID { get; set; }
        public Nullable<System.DateTime> BILLDATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string PAID { get; set; }
        public Nullable<decimal> AMT_PAID { get; set; }
    }
}
