//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEUE_WORKING
    {
        public int ID { get; set; }
        public string FILENAME { get; set; }
        public string WORKFLOW { get; set; }
        public Nullable<int> QUEUE_DEFID { get; set; }
        public string CABINETID { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public Nullable<System.DateTime> LASTACCESSED { get; set; }
        public string VIEWED { get; set; }
        public string PRIORITY { get; set; }
    }
}
