//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEUE_NOTES
    {
        public int ID { get; set; }
        public string FILENAME { get; set; }
        public System.DateTime NOTEDATE { get; set; }
        public string USERNAME { get; set; }
        public string NOTE { get; set; }
    }
}
