//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEUE_DEFINITIONS
    {
        public int ID { get; set; }
        public string WORKFLOW { get; set; }
        public string QUEUE_NAME { get; set; }
        public Nullable<int> QTIME { get; set; }
        public Nullable<int> ONACCEPT { get; set; }
        public Nullable<int> ONREJECT { get; set; }
        public Nullable<int> ONCOMPLETE { get; set; }
        public string STARTINGQUEUE { get; set; }
        public string ENDINGQUEUE { get; set; }
    }
}
