//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_LOG
    {
        public System.DateTime LOGDATE { get; set; }
        public string LOGTYPE { get; set; }
        public string SOURCE { get; set; }
        public string CATEGORY { get; set; }
        public string EVENT { get; set; }
        public string LOGUSER { get; set; }
    }
}
