//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE_DEFINITION
    {
        public string TEMPLATENAME { get; set; }
        public string INDEXNAME { get; set; }
        public short INDEXNUM { get; set; }
        public Nullable<short> MAXLENGTH { get; set; }
        public string DATATYPE { get; set; }
        public string MUSTFILL { get; set; }
        public string MUSTENTER { get; set; }
        public string VIEWINDEX { get; set; }
        public string SEARCHINDEX { get; set; }
        public string OCRACTIVE { get; set; }
        public Nullable<decimal> XCOORDINATE { get; set; }
        public Nullable<decimal> YCOORDINATE { get; set; }
        public Nullable<decimal> ZONEHEIGHT { get; set; }
        public Nullable<decimal> ZONEWIDTH { get; set; }
        public Nullable<short> LINKEDFIELDID { get; set; }
        public string BARCODETYPE { get; set; }
        public string LOOKUP { get; set; }
        public string HIDECOLUMN { get; set; }
    }
}
